name: Publish to PyPI or TestPyPI
description: Upload to a specified PyPI repository
inputs:
  pypi-token:
    required: true
    description: The PyPI API token
  repository-url:
    required: false
    default: https://upload.pypi.org/legacy/
    description: Alternate repository URL (e.g. for TestPyPI)
runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install --upgrade twine
        twine upload --repository-url ${{ inputs.repository-url }} dist/*
      shell: bash
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ inputs.pypi-token }}
