name: Create GitHub Release
description: Creates a GitHub release from a tag
inputs:
  tag_name:
    description: The tag to release
    required: true
  release_title:
    description: Title of the release
    required: true
  release_body:
    description: Body of the release
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        echo "Creating release for ${{ inputs.tag_name }}"
        gh release create "${{ inputs.tag_name }}" \
          --title "${{ inputs.release_title }}" \
          --notes "${{ inputs.release_body }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
