name: Extract version from pyproject.toml
description: Reads the version from pyproject.toml
inputs: {}
outputs:
  version:
    description: The version extracted
runs:
  using: "composite"
  steps:
    - run: |
        VERSION=$(python -c "
import tomllib
with open('pyproject.toml', 'rb') as f:
    print(tomllib.load(f)['project']['version'])
        ")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
