---
# This action extracts the version from  pyproject.toml
inputs:
  input_name:
    description: "Description of the input"
    required: false
outputs:
  version:
    description: The version extracted
    value: ${{ steps.extract_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        VERSION=$(python -c "
import tomllib
with open('pyproject.toml', 'rb') as f:
    print(tomllib.load(f)['project']['version'])
        ")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
