site_name: Ocean4DVarNet Documentation
site_url: https://ebraux.github.io/ocean4dvarnet/
repo_url: https://github.com/ebraux/ocean4dvarnet
#edit_uri: ""
copyright: "Copyright &copy; IMT Atlantique/OceaniX. This software is governed by the CeCILL-C license under French law and abiding by the rules of distribution of free software."

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.footer

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ["ocean4dvarnet", "."]
          options:
            show_source: true
            docstring_style: google


nav:
  - Home: index.md
  - Installing: installing.md
  - Contributing: contributing.md
  - Issues: issues.md
  - Developing:
      - Developing: developing/index.md
      - Guidelines: developing/guidelines.md
      - Fork repository: developing/fork.md
      - Python Environment: developing/environment.md
      - Testing: developing/testing.md
  - Package Documentation:
      - data: pkg-doc/data.md
      - evaluate: pkg-doc/evaluate.md
      - models: pkg-doc/models.md
      - plot: pkg-doc/plot.md
      - process: pkg-doc/process.md
      - train: pkg-doc/train.md
      - utils: pkg-doc/utils.md


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - md_in_html
