site_name: Ocean4DVarNet Documentation
site_url: https://yourdomain.com
repo_url: https://github.com/yourrepo/ocean4dvarnet
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - search.suggest
    - search.highlight

plugins:
  - search
  #- dotenv
  - mkdocstrings:
      handlers:
        python:
          paths: ["contrib", "."]
          options:
            show_source: true
            docstring_style: google


nav:
  - Home: index.md
  - Installing: installing.md
  - Contributing: contributing.md
  - Developing: developing.md
  - API Reference:
      - data: api/data.md
      - evaluate: api/evaluate.md
      - models: api/models.md
      - plot: api/plot.md
      - process: api/process.md
      - train: api/train.md
      - utils: api/utils.md


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - attr_list
  - md_in_html
