name: "Install Python dependencies"
description: "Install pip dependencies (global and local)"
inputs:
  path:
    description: "Path to requirements.txt"
    required: false
    default: "requirements.txt"

runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install --upgrade pip
        echo "Installing dependencies"
        pip install -e .
        echo "Installing dev dependencies"
        pip install -e .[dev]
      shell: bash
